### ISSUE TITLE
NET4_0 symbol never defined so CloudConfigurationManager never used etc

### ISSUE THREAD

**Issue by sickboy** [logentries/le_dotnet#16]
Confirmed by checking the .NET4 dll included in the 2.5 release.

**Comment by StephenHynes7** [comment]
Yep seems to be the root cause for a lot of the issues we are experiencing. I am in the process in the next week to cleaning up the library a bit and will look to remove this.

**Comment by StephenHynes7** [comment]
Should be removed now.
