### ISSUE TITLE
log4net appender does not work under mono 3.12.1

### ISSUE THREAD

**Issue by aleksandrov** [logentries/le_dotnet#19]
Hi All,

I tested following scenarios:
1. my configuration (see below) logs fine under windows
2. I started 
```
sudo tcpdump -i eth0 host data.logentries.com
```
on linux machine with mono 3.12.1 in the first console.

In the second console I executed 
```
telnet data.logentries.com 10000
```
and put some log entry. In result tcpdump prints packets to data.logentries.com. But then I try to tcpdump packets from my application I do not see any traffic to data.logentries.com

My appender configured as:

```xml
        <appender name="LeAppender" type="log4net.Appender.LogentriesAppender, LogentriesLog4net">
            <Debug value="false"/>
            <HttpPut value="false"/>
            <Ssl value="false"/>
            <filter type="log4net.Filter.LevelRangeFilter">
                <levelMin value="INFO"/>
                <levelMax value="FATAL"/>
            </filter>
            <filter type="log4net.Filter.DenyAllFilter"/>
            <layout type="log4net.Layout.PatternLayout">
                <param name="ConversionPattern" value="%d{ddd MMM dd HH:mm:ss zzz yyyy} %logger %: %level%, %m, "/>
            </layout>
        </appender>
```

My packages.config is
```xml
<packages>
  <package id="log4net" version="2.0.3" targetFramework="net45" />
  <package id="logentries.core" version="2.6.7" targetFramework="net45" />
  <package id="logentries.log4net" version="2.6.3" targetFramework="net45" />
</packages>
```

Please let me know in case of questions!

Thank you,
Dmytro

**Comment by StephenHynes7** [comment]
Hey Dmytro,

I know the log4net setup can be a pain in the ass. Are you setting packages.conifg to be copyed to the output directory? 

Also does the application terminate immediately? Note that it is asynchronous library so it may take a second before the tasks completes.

Regards,
Stephen

**Comment by aleksandrov** [comment]
1. No, provided packages.config just for reference to show libraries version which I use
2. No, application runs as 24/7 service.

**Comment by aleksandrov** [comment]
same issues reproduced with mono 4.0.1

**Comment by aleksandrov** [comment]
It looks like CloudConfigurationManager fails under mono environment. Thats why asyncLogger unable to read  cloud config

**Comment by aleksandrov** [comment]
PR #26 added

**Comment by aleksandrov** [comment]
PR #26 applied
