### ISSUE TITLE
Nuget package has old code that does not work

### ISSUE THREAD

**Issue by MartinWa** [logentries/le_dotnet#23]
Could you please update the nuget package with the latest fixes? I have problems running the log in Azure but when I switch to code compiled from github it works. I think it is the last commit (fa6af7d5ca19c66f85ab6d34bbd74dd8ec3a5c1e) that fixed the problems I see.

**Comment by StephenHynes7** [comment]
Hey Martin, ill look into this in the next hour or so. When I had tested the package I ended up getting errors so I held back from pushing any changes to Nuget. Hopefully should be sorted today.

**Comment by StephenHynes7** [comment]
This should be fixed now in the latest version on nuget.
