### ISSUE TITLE
Nuget 2.7.0 includes assemblies from 2.6.7

### ISSUE THREAD

**Issue by aleksandrov** [logentries/le_dotnet#28]
Hi All, 

Just tried to find my PR in new nuget package, but found just old dlls :-)

Regards,
Dmitry

**Comment by StephenHynes7** [comment]
Huh, let me double check that everything was uploaded correctly! Sorry about that.

**Comment by StephenHynes7** [comment]
Yep my bad uploaded the wrong DLL's, should be fixed now, version numbers of nuget should be bumped up one. (2.7.1 and 2.5.1)
