### ISSUE TITLE
nlog appender does not work under mono

### ISSUE THREAD

**Issue by zloom** [logentries/le_dotnet#31]
Hi i found this issue https://github.com/logentries/le_dotnet/pull/26
It still does not work if mono runned under windows. I suggest to use previous solution but check is it runs on mono.

http://stackoverflow.com/questions/721161/how-to-detect-which-net-runtime-is-being-used-ms-vs-mono

**Comment by StephenHynes7** [comment]
Interesting @aleksandrov can you confirm?

**Comment by aleksandrov** [comment]
I think that solution provided by @zloom is more correct that mine. I can check how it works under mono+linux and let you know shortly

**Comment by aleksandrov** [comment]
yep, works fine! PR #32 added
