### ISSUE TITLE
Allow defining the token from another provider

### ISSUE THREAD

**Issue by israelolcha** [logentries/le_dotnet#35]
Create an extension that allows setting the token from another source.

**Comment by kamranayub** [comment]
You can programmatically set the token if you want although it's not well-documented.

```
string logEntriesToken = ConfigurationManager.AppSettings["MySpecificLogEntriesToken"];

if (logEntriesToken != null)
{
  var target = (LogentriesTarget)LogManager.Configuration.FindTargetByName("Logentries");

  target.Token = logEntriesToken;
}
```

I use this method in Azure because I have multiple jobs and want to send them to multiple logs.

**Comment by aaronclawrence-itl** [comment]
In my opinion Kamranayub's solution answers this issue and it should probably be closed. Any comment israelolcha ? (PS. I'm not a logentries developer, so I can't actually close it)
