### ISSUE TITLE
The .Net library web.config example is incorrect

### ISSUE THREAD

**Issue by michaelgwelch** [logentries/le_dotnet#38]
On July 16 I created a new log and followed the guidance for the .Net library. It asked me to paste the following into my Web.config

    <configSections>
      <section name="log4net" type="log4net.Config.Log4NetConfigurationSectionHandler, log4net" />
    </configSections>
    <log4net>
      <appender name="LeAppender" type="log4net.Appender.LogentriesAppender, LogentriesLog4net">
        <Debug value="true" />
        <HttpPut value="false" />
        <Ssl value="false" />
        <layout type="log4net.Layout.PatternLayout">
          <param name="ConversionPattern" value="%d{ddd MMM dd HH:mm:ss zzz yyyy} %logger %: %level%, %m, " />
        </layout>
      </appender>
      <root>
        <level value="ALL" />
        <appender-ref ref="LeAppender" />
      </root>
    </log4net>

You'll noticed in the appender section it references the dll `LogentriesLog4net`. However, in the Nuget package I downloaded yesterday the actual dll I needed to reference is `LeLog4net`. The name of the Nuget package was `Logentries Plugin for Log4net[1.2.11]` and its version was 2.3.7

You may want to update the example config code.

**Comment by michaelgwelch** [comment]
I just noticed the README https://github.com/logentries/le_dotnet has the same guidance. It specifically talks about LogentriesLog4net. (Did I grab an old Nuget package of the name of your dll recently change?)

**Comment by StephenHynes7** [comment]
@michaelgwelch what installation command did you run?

**Comment by michaelgwelch** [comment]
No command. Used the gui in visual studio.

Now I just searched for `logentries.log4net` and I see 5 entries (one of them deprecated). Just tried to install what looked like the latest version and now I see an assembly called LogentriesCore and it only has an AsyncAppender (no LeAppender).  I guess I'll uninstall and reinstall one more time.

What version (name and version, since there are a couple different names) do you recommend?

**Comment by michaelgwelch** [comment]
Now I'm following the guidance from here: https://www.nuget.org/packages/logentries.log4net

    Install-Package logentries.log4net

But again I don't see LogentriesLog4net in the list of project references after the install.

**Comment by michaelgwelch** [comment]
Looked in my packages folder after the install

    $ ls logentries.core.2.7.1/lib/net40/
    LogentriesCore.dll
    $ ls logentries.log4net.2.7.1/lib/net40/
    LogentriesCore.dll

Does the current nuget package bundle the wrong dll? I see LogentreCore.dll in both logentries.core and logentries.log4net.

Or is Nuget screwing up?

**Comment by michaelgwelch** [comment]
For now I reverted back to the old version I had (le_log4net.2.3.7). With this version logs stop as soon as I set ssl=true. Perhaps there is/was an issue with ssl in this old version. I'll await an answer on this current issue and once I get the latest version of log entries to install properly I'll try ssl again.

Finally, just in case nuget screwed up my environment, I'll start with a fresh project and see if everything installs and works properly.

**Comment by StephenHynes7** [comment]
The much older versions won't work due to changes in our SSL certificates hence why you may see errors though it's been that long ago I can't remember the version off the top of my head.

I have a sample app [here](https://github.com/StephenHynes7/LogentriesSampleApps/tree/master/LogentriesLog4NetSampleApp) you can use for comparison

**Comment by michaelgwelch** [comment]
@StephenHynes7 I'll install the same version of log entries that you used in the sample app. If you use the latest 2.7.1 you won't get the assemblies you need. I tried with a brand new sample app and the package directory `logentries.log4net.2.7.1/lib/net40/` only contains LogentriesCore.dll

**Comment by michaelgwelch** [comment]
See #39. All my problems are resolved now.

**Comment by michaelgwelch** [comment]
@StephenHynes7  Please see #33. Your current Nuget Package is broken.

**Comment by michaelgwelch** [comment]
@StephenHynes7 another user just reported issue with #33. You responded pretty quickly to this issue and one other I had. It's odd no one has addressed #33 yet.
