### ISSUE TITLE
Is this line `[assembly: XmlConfigurator(Watch = true)]` required?

### ISSUE THREAD

**Issue by michaelgwelch** [logentries/le_dotnet#39]
I found that once I set up my logging I didn't see any log messages. After some googling I saw a mention of adding this line somewhere in my project:

    [assembly: XmlConfigurator(Watch = true)]

I see no mention of this in your own documentation. But I have noticed that without this line, my logging stops. So I just wanted to clarify that it is required or I'm doing something else wrong.

**Comment by StephenHynes7** [comment]
I haven't seen that before. The only thing I can think of is that sometimes I needed to make sure that my App/Web.config would need to copy to the output directory before log4net would pick it up. Possible that it is related.

**Comment by michaelgwelch** [comment]
Odd that you haven't seen it. Here's a SO thread: http://stackoverflow.com/questions/10204171/configure-log4net-in-web-application

Logging works fine for me with the assembly attribute above and an old version of Logentries (le_log4net version 2.3.7). No luck at all getting Logentries (2.6.3) working in a web app (with or without this XmlConfigurator).

By the way the sample console app you pointed me to in #38 works fine locally. Not sure what is different about my web app. Like I said, everything is fine with the old version of logentries (except I can't get ssl to work).

With version 2.6.3 I'm seeing this in my debug output (if I set XmlConfigurator, if I don't set that attribute then I see nothing in my debug window).

    LE: LE - Adding Line: line
    LE: LE - Adding Line: line
    LE: LE - Adding Line: line
    LE: LE - Adding Line: line

This would seem to indicate to me that Logentries is working. But nothing shows up in my log.

**Comment by michaelgwelch** [comment]
The only way I got the current version to work is to checkout the source code add LogentriesAppender to my own project and compile locally. Literally, without changing anything else in my project or web.config (except the assembly name), now it works.

**Comment by michaelgwelch** [comment]
I finally got plain text and ssl logging to work. I had to ensure I used the exact same versions of log4net, logentries.core, and logentries.log4net that you did.

    <packages>
      <package id="log4net" version="2.0.3" targetFramework="net45" />
      <package id="logentries.core" version="2.7.1" targetFramework="net45" />
      <package id="logentries.log4net" version="2.6.3" targetFramework="net45" />
      <package id="Microsoft.WindowsAzure.ConfigurationManager" version="3.1.0" targetFramework="net45" />
    </packages>
