### ISSUE TITLE
Improve Nlog integration documentation

### ISSUE THREAD

**Issue by lalberto8085** [logentries/le_dotnet#48]
Right now must of NLog documentation is just a clone of log4net's, aside from samples. It could sometimes be misleading to some users I think it would be helpful to fix this in order to make documentation clearer.

**Comment by gearoidof-r7** [comment]
@KieranOBrien-R7 will have a look into this, thanks for the heads up @lalberto8085

**Comment by KieranOBrien-R7** [comment]
@lalberto8085 I have updated the README to point towards our docs which are specific to the library. I'll close this issue.
