### ISSUE TITLE
Specific version of NLog required

### ISSUE THREAD

**Issue by valentin-turcu** [logentries/le_dotnet#5]
The latest (2.2.0) version of the LogentriesNlog package requires a specific version of NLog (2.0.1.1) to function correctly. 
If I use any NLog version beyond that, I get a conflict of NLog DLL versions on build, and a runtime error of "Unable to load assembly NLog 2.0.1.1, provided version is 2.x.y.z". 
To get past it, I have to use dependency redirects in App/Web.config's like this: 
```xml
<dependentAssembly>
    <assemblyIdentity name="NLog" publicKeyToken="5120e14c03d0593c" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-2.1.0.0" newVersion="2.1.0.0" />
</dependentAssembly>
```
Problem is, especially for large solutions, putting code blocks in all the configuration files is undesirable. 
Additional data to help replicate the issue:
I'm using the programmatic configuration for NLog, and the only project that references NLog is my standalone logging library. Everything else just references my logging library and calls the NLog logger through a simple static logging interface I created.

**Comment by StephenHynes7** [comment]
Changed this so it will now use the latest version of Nlog.
